/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thangqt' at '4/17/20 7:39 AM' with Gradle 2.10
 *
 * @author thangqt, @date 4/17/20 7:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
